global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: ticketReserve
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:8080"
          - "host.docker.internal:8081"
          - "host.docker.internal:8082"
        labels:
          app: ticketReserve
